@endpoint=http://localhost:{{$dotenv PORT}}

###
POST {{endpoint}}
Content-Type: application/json
X-Request-Type: GraphQL

query user($id: Int!) {
  user(id: $id) {
    id
    pseudo
    temperature
  }
}

{
  "id": 1
}

###
GET http://api.weatherapi.com/v1/current.json?key={{$dotenv WEATHER_API_KEY}}&q=Paris